# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('time', models.DateField(default=datetime.datetime.now)),
                ('file_type', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
